W7D2/music_project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy] 
  resources :bands
end

W7D2/music_project/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true
end

W7D2/music_project/app/models/user.rb
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true 
    validates :password_digest, presence: true 

    attr_reader :password #reader method for password
    after_initialize :ensure_session_token #use a callback to set the session_token before validation if it's not present
    
    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    def self.generate_session_token 
        SecureRandom::urlsafe_base64
    end 

    def reset_session_token! 
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end 

    def ensure_session_token 
        self.session_token ||= User.generate_session_token
    end 

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def password=(password) #password setter method, required since this is not a part of the db
        @password = password  # Create a new instance variable, @password, to use for validation later
        self.password_digest = BCrypt::Password.create(password)  # Use the built in setter for password digest (ActiveRecord) to assign the hash
    end

end

W7D2/music_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user 
    helper_method :logged_in?
    helper_method :login_user! 

    private 

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end 

    def logged_in?
        !@current_user.nil?
    end 

    def login_user!(user)
        session[:session_token] = user.reset_session_token!
    end 

    def logout_user!
        current_user.reset_session_token!
        session[:session_token] = nil
    end
 
    def require_no_user!
        redirect_to session_url if current_user
    end

end

W7D2/music_project/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def index 
        @bands = Band.all 
    end 

    def create 
        band = Band.create(new_band_params)
        if band.save 
            redirect_to band_url(band)
        else   
            render :new
        end
    end 

    def new 
        @band = Band.new
        render :new
    end 

    def edit 
        @band = Band.find(params[:id])
        render :edit
    end 

    def show 
        @band = Band.find(params[:id])
        render :show
    end 

    def update 
        @band = Band.find(params[:id])
        if @band.update_attributes(new_band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end 

    def destroy
        band = Band.find(params[:id])
        band.destroy
        redirect_to bands_url
    end

    private 

    def new_band_params
        params.require(:band).permit(:name)
    end 
end

W7D2/music_project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_no_user!, only: %i(create new)

    def create 
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if user.nil?
            flash.now[:errors] = ["Incorrect email and/or password"]
            render :new
        else  
            login_user!(user) # resets the session_token and session[:session_token]
            redirect_to user_url(user)
        end 
    end

    def destroy 
        logout_user!
        redirect_to new_session_url
    end 

    def new 
        render :new
    end
end

W7D2/music_project/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def create 
        @user = User.new(user_params)
        if @user.save 
            login_user!(@user)
            # redirect_to  will jump back to this later!
        else   
            flash.now[:errors] = @user.errors.full_messages #if login is not successful, render new 
            render :new
        end
    end 

    def show 
        @user = User.find(params[:id])
        render :show
    end

    def new 
        @user = User.new 
        render :new
    end 

    private 

    def user_params 
        params.require(:user).permit(:email, :password)
    end
end

W7D2/music_project/app/helpers/bands_helper.rb
module BandsHelper
end

W7D2/music_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <nav class="main-nav">
    <h1><a href="<%= %>"><font size="20" face="impact" color="teal">M U S I C  A P P</font></a></h1>
    <div>
    <% if !logged_in? %>
      <a href="<%= new_session_url %>">SIGN IN </a>
      <a href="<%= new_user_url %>">SIGN UP</a>
    <% else %>
      <%= current_user.email %>
      <form action="<%= session_url %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Logout">
      </form>
    <% end %>
    </div>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

W7D2/music_project/app/views/users/new.html.erb
<section class="page">
  <div class="centered-box">
    <h1>CREATE AN ACCOUNT</h1>


    <form action="<%= users_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="user_email">User Email</label>
      <input type="text"
        name="user[email]"
        id="user_username"
        value="<%= @user.email %>">
      <br>

      <label for="user_password">Password</label>
      <input type="password"
        name="user[password]"
        id="user_password"
        value="<%= @user.password %>">
      <br>

      <input type="submit">
    </form>
  </div>
</section>

W7D2/music_project/app/views/users/show.html.erb
<h1><%= current_user.email %></h1>